### ISSUE TITLE
Use `xquery` instead of `xmlpath`

### ISSUE THREAD

**Issue by grubernaut** [dylanmei/winrmtest#3]
Due to licensing constraints, we're unable to consume any LGPL licenses in our project. The dependency `xmlpath` uses LGPL, and therefore we are unable to use this library. 

If it would be at all possible to use https://github.com/antchfx/xquery instead, without incurring any breaking changes, that would be amazing. 

Thanks!

**Comment by dylanmei** [comment]
This is a very interesting ask and I'm totally into the idea.

**Comment by dylanmei** [comment]
Fixed by merged PR #4
